"""Models for contact"""

from pydantic import BaseModel, UUID4


class ContactModel(BaseModel):
    """Contact pydantic model"""

    id: UUID4
    name: str
    email: str
    phone: str
    address: str


class InsertContactModel(BaseModel):
    """
    Insert contact pydantic model for creating new contact
    Took out id field because it is automatically generated by the database
    """

    name: str
    email: str
    phone: str
    address: str
